[Writable]
Persistence = 'database'
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'edgex-support-logging'
Port = 48061
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the Support Logging Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = '/edgex/logs/edgex-support-logging.log'

[Databases]
  [Databases.Primary]
  Host = 'edgex-mongo'
  Name = 'logging'
  Password = 'password'
  Port = 27017
  Username = 'logging'
  Timeout = 5000
  Type = 'mongodb'